services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./conspiracy:/app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data: