<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260925120950 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sinje (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, userid BIGINT NOT NULL, lastuser BIGINT NOT NULL, possession BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sinje_cooldown (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cooldown INT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE sinje');
        $this->addSql('DROP TABLE sinje_cooldown');
    }
}
