<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260926120908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE l9low (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, low VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE l9prefix (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prefix VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE l9verb (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, verb VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE l9low');
        $this->addSql('DROP TABLE l9prefix');
        $this->addSql('DROP TABLE l9verb');
    }
}
